package com.lewis.base.entity;

import java.io.Serializable;

public class Chat implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.gid
     *
     * @mbg.generated
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.sname
     *
     * @mbg.generated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.gname
     *
     * @mbg.generated
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.simg
     *
     * @mbg.generated
     */
    private String simg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.gimg
     *
     * @mbg.generated
     */
    private String gimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.time
     *
     * @mbg.generated
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.sessionid
     *
     * @mbg.generated
     */
    private Integer sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.id
     *
     * @return the value of chat.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.id
     *
     * @param id the value for chat.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.sid
     *
     * @return the value of chat.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.sid
     *
     * @param sid the value for chat.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.gid
     *
     * @return the value of chat.gid
     *
     * @mbg.generated
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.gid
     *
     * @param gid the value for chat.gid
     *
     * @mbg.generated
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.sname
     *
     * @return the value of chat.sname
     *
     * @mbg.generated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.sname
     *
     * @param sname the value for chat.sname
     *
     * @mbg.generated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.gname
     *
     * @return the value of chat.gname
     *
     * @mbg.generated
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.gname
     *
     * @param gname the value for chat.gname
     *
     * @mbg.generated
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.simg
     *
     * @return the value of chat.simg
     *
     * @mbg.generated
     */
    public String getSimg() {
        return simg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.simg
     *
     * @param simg the value for chat.simg
     *
     * @mbg.generated
     */
    public void setSimg(String simg) {
        this.simg = simg == null ? null : simg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.gimg
     *
     * @return the value of chat.gimg
     *
     * @mbg.generated
     */
    public String getGimg() {
        return gimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.gimg
     *
     * @param gimg the value for chat.gimg
     *
     * @mbg.generated
     */
    public void setGimg(String gimg) {
        this.gimg = gimg == null ? null : gimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.time
     *
     * @return the value of chat.time
     *
     * @mbg.generated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.time
     *
     * @param time the value for chat.time
     *
     * @mbg.generated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.content
     *
     * @return the value of chat.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.content
     *
     * @param content the value for chat.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.sessionid
     *
     * @return the value of chat.sessionid
     *
     * @mbg.generated
     */
    public Integer getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.sessionid
     *
     * @param sessionid the value for chat.sessionid
     *
     * @mbg.generated
     */
    public void setSessionid(Integer sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sid=").append(sid);
        sb.append(", gid=").append(gid);
        sb.append(", sname=").append(sname);
        sb.append(", gname=").append(gname);
        sb.append(", simg=").append(simg);
        sb.append(", gimg=").append(gimg);
        sb.append(", time=").append(time);
        sb.append(", content=").append(content);
        sb.append(", sessionid=").append(sessionid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}